ifdef CROSS_COMPILE
CC 	= $(CROSS_COMPILE)gcc
CXX = $(CROSS_COMPILE)g++
CPP = $(CC) -E
AS 	= $(CROSS_COMPILE)as
LD	= $(CROSS_COMPILE)ld
AR	= $(CROSS_COMPILE)ar
NM	= $(CROSS_COMPILE)nm
STRIP 	= $(CROSS_COMPILE)strip
OBJCOPY 	= $(CROSS_COMPILE)objcopy
endif

STRIP ?= strip

LVGL_DIR_NAME 	?= lvgl
LVGL_DIR 		?= .

WARNINGS		:= -Wall -Wextra -Wno-unused-function -Wno-error=strict-prototypes -Wpointer-arith \
					-fno-strict-aliasing -Wno-error=cpp -Wuninitialized -Wmaybe-uninitialized -Wno-unused-parameter -Wno-missing-field-initializers -Wtype-limits -Wsizeof-pointer-memaccess \
					-Wno-format-nonliteral -Wno-cast-qual -Wunreachable-code -Wno-switch-default -Wreturn-type -Wmultichar -Wformat-security -Wno-error=pedantic \
					-Wno-sign-compare -Wdouble-promotion -Wclobbered -Wempty-body -Wtype-limits -Wshift-negative-value
CFLAGS 			?= -O3 -g0 -MD -MP -I$(LVGL_DIR)/ $(WARNINGS)
LDFLAGS 		?= -static -lm -Llibhv/lib -l:libhv.a -latomic -lpthread -Lwpa_supplicant/wpa_supplicant/ -l:libwpa_client.a -lstdc++fs
BIN 			= bootstrap
BUILD_DIR 		= ./build-bootstrap
BUILD_OBJ_DIR 	= $(BUILD_DIR)/obj
BUILD_BIN_DIR 	= $(BUILD_DIR)/bin

BOOTSTRAP_SRC = \
	$(LVGL_DIR)/src/bootstrap/main.cpp \
	$(LVGL_DIR)/src/net_utils.cpp \
	$(LVGL_DIR)/src/button_container.cpp \
	$(LVGL_DIR)/src/wifi_panel.cpp \
	$(LVGL_DIR)/src/wpa_event.cpp

include $(LVGL_DIR)/lvgl/lvgl.mk
include $(LVGL_DIR)/lv_drivers/lv_drivers.mk

CSRCS 			+= $(wildcard $(LVGL_DIR)/assets/*.c)
ifdef GUPPY_CALIBRATE
CSRCS			+= $(wildcard $(LVGL_DIR)/lv_touch_calibration/*.c)
DEFINES			+= -D GUPPY_CALIBRATE
DEFINES			+= -D EVDEV_CALIBRATE
endif

ASSET_DIR		= material
ifdef GUPPY_SMALL_SCREEN
ASSET_DIR		= material_46
DEFINES			+= -D GUPPY_SMALL_SCREEN
endif

CSRCS 			+= $(wildcard $(LVGL_DIR)/assets/$(ASSET_DIR)/*.c)

ifdef GUPPY_WAYLAND
WAYLAND_SCANNER := $(shell command -v wayland-scanner 2>/dev/null)
WAYLAND_PROTOCOLS_BASE := $(shell pkg-config --variable=pkgdatadir wayland-protocols 2>/dev/null)
WAYLAND_CFLAGS := $(shell pkg-config --cflags wayland-client wayland-cursor xkbcommon 2>/dev/null)
WAYLAND_LIBS := $(shell pkg-config --libs wayland-client wayland-cursor xkbcommon 2>/dev/null)
ifeq ($(strip $(WAYLAND_PROTOCOLS_BASE)),)
WAYLAND_PROTOCOLS_BASE := $(shell test -d /usr/share/wayland-protocols && printf %s /usr/share/wayland-protocols)
endif
ifeq ($(strip $(WAYLAND_LIBS)),)
WAYLAND_LIBS := -lwayland-client -lwayland-cursor -lxkbcommon
endif
WAYLAND_XDG_PROTOCOL := $(WAYLAND_PROTOCOLS_BASE)/stable/xdg-shell/xdg-shell.xml
WAYLAND_PROTOCOL_GEN_DIR := $(BUILD_DIR)/wayland-src/protocols
WAYLAND_PROTOCOL_GEN_C := $(WAYLAND_PROTOCOL_GEN_DIR)/wayland-xdg-shell-client-protocol.c
WAYLAND_PROTOCOL_GEN_H := $(WAYLAND_PROTOCOL_GEN_DIR)/wayland-xdg-shell-client-protocol.h
WAYLAND_PROTOCOL_OBJ := $(BUILD_OBJ_DIR)/$(patsubst ./%,%,$(WAYLAND_PROTOCOL_GEN_C:.c=.o))
WAYLAND_SRC_OBJ := $(BUILD_OBJ_DIR)/lv_drivers/wayland/wayland.o

CSRCS			+= $(WAYLAND_PROTOCOL_GEN_C)
endif

ifdef GUPPYSCREEN_VERSION
SHORT_GUPPYSCREEN_VERSION := $(shell printf "%s" "$(GUPPYSCREEN_VERSION)" | cut -c1-7)
DEFINES			+= -D GUPPYSCREEN_VERSION=\"$(SHORT_GUPPYSCREEN_VERSION)\"
else
DEFINES			+= -D GUPPYSCREEN_VERSION=\"unknown\"
endif

OBJEXT 			?= .o

AOBJS 			= $(ASRCS:.S=$(OBJEXT))
COBJS 			= $(CSRCS:.c=$(OBJEXT))
MAINOBJ 		= $(BOOTSTRAP_SRC:.cpp=$(OBJEXT))
DEPS            = $(addprefix $(BUILD_OBJ_DIR)/, $(patsubst %.o, %.d, $(MAINOBJ)))
OBJS 			= $(AOBJS) $(COBJS) $(MAINOBJ)
TARGET 			= $(addprefix $(BUILD_OBJ_DIR)/, $(patsubst ./%, %, $(OBJS)))

INC 			:= -I./ -I./src -I./lvgl/ -I./lv_touch_calibration -I./fmt/include -I./libhv/include -I./wpa_supplicant/src/common
LDLIBS	 		:= -lm
DEFINES			+= -D _GNU_SOURCE -DSPDLOG_COMPILED_LIB

ifdef GUPPY_WAYLAND
ifeq ($(strip $(WAYLAND_SCANNER)),)
$(error GUPPY_WAYLAND=1 requires wayland-scanner to be installed)
endif
ifeq ($(strip $(WAYLAND_PROTOCOLS_BASE)),)
$(error GUPPY_WAYLAND=1 requires wayland-protocols; could not locate pkgdatadir)
endif
ifeq ($(wildcard $(WAYLAND_XDG_PROTOCOL)),)
$(error GUPPY_WAYLAND=1 requires xdg-shell.xml at $(WAYLAND_XDG_PROTOCOL))
endif
LDFLAGS				:= -no-pie $(filter-out -static,$(LDFLAGS))
INC					+= -I./lv_drivers/wayland -I./$(BUILD_DIR)/wayland-src $(WAYLAND_CFLAGS)
LDFLAGS				+= $(WAYLAND_LIBS)
DEFINES				+= -D GUPPY_WAYLAND -D USE_WAYLAND=1 -D LV_WAYLAND_XDG_SHELL=1 -D LV_WAYLAND_WL_SHELL=1
endif

COMPILE_CC		= $(CC) $(CFLAGS) $(INC) $(DEFINES)
COMPILE_CXX	= $(CXX) $(CFLAGS) $(INC) $(DEFINES)

all: default

libhv.a:
	$(MAKE) -C libhv -j$(nproc) libhv

wpaclient:
	$(MAKE) -C wpa_supplicant/wpa_supplicant -j$(nproc) libwpa_client.a

ifdef GUPPY_WAYLAND
$(WAYLAND_PROTOCOL_GEN_C) $(WAYLAND_PROTOCOL_GEN_H): $(WAYLAND_XDG_PROTOCOL)
	@mkdir -p $(WAYLAND_PROTOCOL_GEN_DIR)
	$(WAYLAND_SCANNER) client-header $< $(WAYLAND_PROTOCOL_GEN_H)
	$(WAYLAND_SCANNER) private-code $< $(WAYLAND_PROTOCOL_GEN_C)

$(WAYLAND_SRC_OBJ): $(WAYLAND_PROTOCOL_GEN_H)
$(WAYLAND_PROTOCOL_OBJ): $(WAYLAND_PROTOCOL_GEN_H)
endif

$(BUILD_OBJ_DIR)/%.o: %.cpp
	@mkdir -p $(dir $@)
	@$(COMPILE_CXX) -std=c++17 $(CFLAGS) -c $< -o $@
	@echo "CXX $<"

$(BUILD_OBJ_DIR)/%.o: %.c
	@mkdir -p $(dir $@)
	@$(COMPILE_CC) $(CFLAGS) -c $< -o $@
	@echo "CC $<"

default: libhv.a wpaclient $(TARGET)
	@mkdir -p $(dir $(BUILD_BIN_DIR)/)
	$(CXX) -o $(BUILD_BIN_DIR)/$(BIN) $(TARGET) $(LDFLAGS) $(LDLIBS)
	@$(STRIP) $(BUILD_BIN_DIR)/$(BIN)

libhvclean:
	$(MAKE) -C libhv clean

wpaclean:
	$(MAKE) -C wpa_supplicant/wpa_supplicant clean

clean:
	rm -rf $(BUILD_DIR)

-include $(DEPS)
